window.flightData = [
  {
    "id": "fuk-01",
    "city": "Fukuoka",
    "country": "Japan",
    "airport": "FUK",
    "origin": "ICN",
    "airline": "Air Seoul",
    "depart": "Fri 19:40",
    "arrive": "Fri 21:05",
    "returnDepart": "Sun 20:10",
    "returnArrive": "Sun 21:35",
    "price": 218000,
    "leave": 0,
    "score": 96,
    "mode": "balanced",
    "category": [
      "weekend",
      "commuter",
      "monday",
      "deal"
    ],
    "tag": "No leave needed",
    "gateBuffer": 48,
    "commuteBuffer": 42,
    "immigrationOut": 66,
    "immigrationIn": 54,
    "fatigue": "Low",
    "image": "assets/img/portfolio/1.jpg"
  },
  {
    "id": "tpe-02",
    "city": "Taipei",
    "country": "Taiwan",
    "airport": "TPE",
    "origin": "ICN",
    "airline": "T'way Air",
    "depart": "Fri 20:15",
    "arrive": "Fri 22:05",
    "returnDepart": "Mon 00:20",
    "returnArrive": "Mon 03:55",
    "price": 298000,
    "leave": 0.5,
    "score": 91,
    "mode": "balanced",
    "category": [
      "weekend",
      "commuter",
      "monday"
    ],
    "tag": "Monday half-day suggested",
    "gateBuffer": 36,
    "commuteBuffer": 31,
    "immigrationOut": 72,
    "immigrationIn": 58,
    "fatigue": "Medium",
    "image": "assets/img/portfolio/2.jpg"
  },
  {
    "id": "osa-03",
    "city": "Osaka",
    "country": "Japan",
    "airport": "KIX",
    "origin": "GMP",
    "airline": "Jeju Air",
    "depart": "Sat 08:20",
    "arrive": "Sat 10:05",
    "returnDepart": "Sun 19:35",
    "returnArrive": "Sun 21:25",
    "price": 246000,
    "leave": 0,
    "score": 84,
    "mode": "relaxed",
    "category": [
      "weekend",
      "deal"
    ],
    "tag": "Weekend compact",
    "gateBuffer": 75,
    "commuteBuffer": 58,
    "immigrationOut": 62,
    "immigrationIn": 50,
    "fatigue": "Low",
    "image": "assets/img/portfolio/3.jpg"
  },
  {
    "id": "dad-04",
    "city": "Da Nang",
    "country": "Vietnam",
    "airport": "DAD",
    "origin": "ICN",
    "airline": "Vietjet Air",
    "depart": "Thu 22:35",
    "arrive": "Fri 01:25",
    "returnDepart": "Sun 23:55",
    "returnArrive": "Mon 06:10",
    "price": 386000,
    "leave": 1,
    "score": 88,
    "mode": "max",
    "category": [
      "leave",
      "maxplay",
      "monday"
    ],
    "tag": "One leave day efficient",
    "gateBuffer": 52,
    "commuteBuffer": 46,
    "immigrationOut": 84,
    "immigrationIn": 70,
    "fatigue": "High",
    "image": "assets/img/portfolio/4.jpg"
  },
  {
    "id": "bkk-05",
    "city": "Bangkok",
    "country": "Thailand",
    "airport": "BKK",
    "origin": "ICN",
    "airline": "Jin Air",
    "depart": "Fri 21:20",
    "arrive": "Sat 01:10",
    "returnDepart": "Mon 02:30",
    "returnArrive": "Mon 10:05",
    "price": 422000,
    "leave": 1,
    "score": 82,
    "mode": "max",
    "category": [
      "maxplay",
      "leave"
    ],
    "tag": "Long night flight",
    "gateBuffer": 44,
    "commuteBuffer": 34,
    "immigrationOut": 92,
    "immigrationIn": 88,
    "fatigue": "High",
    "image": "assets/img/portfolio/5.jpg"
  },
  {
    "id": "sin-06",
    "city": "Singapore",
    "country": "Singapore",
    "airport": "SIN",
    "origin": "ICN",
    "airline": "Scoot",
    "depart": "Thu 23:10",
    "arrive": "Fri 04:55",
    "returnDepart": "Sun 22:40",
    "returnArrive": "Mon 06:10",
    "price": 512000,
    "leave": 1,
    "score": 79,
    "mode": "balanced",
    "category": [
      "leave",
      "monday"
    ],
    "tag": "City sprint",
    "gateBuffer": 58,
    "commuteBuffer": 47,
    "immigrationOut": 78,
    "immigrationIn": 64,
    "fatigue": "Medium",
    "image": "assets/img/portfolio/6.jpg"
  },
  {
    "id": "hkg-07",
    "city": "Hong Kong",
    "country": "Hong Kong",
    "airport": "HKG",
    "origin": "ICN",
    "airline": "HK Express",
    "depart": "Fri 20:55",
    "arrive": "Fri 23:45",
    "returnDepart": "Sun 21:50",
    "returnArrive": "Mon 02:25",
    "price": 334000,
    "leave": 0.5,
    "score": 86,
    "mode": "balanced",
    "category": [
      "weekend",
      "commuter"
    ],
    "tag": "Late return",
    "gateBuffer": 40,
    "commuteBuffer": 30,
    "immigrationOut": 80,
    "immigrationIn": 60,
    "fatigue": "Medium",
    "image": "assets/img/portfolio/1.jpg"
  },
  {
    "id": "nrt-08",
    "city": "Tokyo",
    "country": "Japan",
    "airport": "NRT",
    "origin": "ICN",
    "airline": "ZIPAIR",
    "depart": "Fri 18:55",
    "arrive": "Fri 21:15",
    "returnDepart": "Sun 18:20",
    "returnArrive": "Sun 21:00",
    "price": 289000,
    "leave": 0,
    "score": 90,
    "mode": "balanced",
    "category": [
      "weekend",
      "commuter",
      "monday"
    ],
    "tag": "Tight but clean",
    "gateBuffer": 28,
    "commuteBuffer": 24,
    "immigrationOut": 68,
    "immigrationIn": 55,
    "fatigue": "Low",
    "image": "assets/img/portfolio/2.jpg"
  },
  {
    "id": "ngo-09",
    "city": "Nagoya",
    "country": "Japan",
    "airport": "NGO",
    "origin": "ICN",
    "airline": "Korean Air",
    "depart": "Sat 09:05",
    "arrive": "Sat 10:55",
    "returnDepart": "Mon 07:25",
    "returnArrive": "Mon 09:35",
    "price": 351000,
    "leave": 0.5,
    "score": 77,
    "mode": "relaxed",
    "category": [
      "monday",
      "relaxed"
    ],
    "tag": "Monday late start",
    "gateBuffer": 82,
    "commuteBuffer": 61,
    "immigrationOut": 60,
    "immigrationIn": 52,
    "fatigue": "Medium",
    "image": "assets/img/portfolio/3.jpg"
  },
  {
    "id": "cebu-10",
    "city": "Cebu",
    "country": "Philippines",
    "airport": "CEB",
    "origin": "ICN",
    "airline": "Cebu Pacific",
    "depart": "Fri 22:10",
    "arrive": "Sat 01:35",
    "returnDepart": "Mon 01:20",
    "returnArrive": "Mon 06:45",
    "price": 372000,
    "leave": 1,
    "score": 81,
    "mode": "max",
    "category": [
      "maxplay",
      "leave"
    ],
    "tag": "Beach max time",
    "gateBuffer": 49,
    "commuteBuffer": 36,
    "immigrationOut": 88,
    "immigrationIn": 74,
    "fatigue": "High",
    "image": "assets/img/portfolio/4.jpg"
  },
  {
    "id": "pvg-11",
    "city": "Shanghai",
    "country": "China",
    "airport": "PVG",
    "origin": "ICN",
    "airline": "China Eastern",
    "depart": "Fri 19:25",
    "arrive": "Fri 20:40",
    "returnDepart": "Sun 18:45",
    "returnArrive": "Sun 21:55",
    "price": 265000,
    "leave": 0,
    "score": 87,
    "mode": "balanced",
    "category": [
      "weekend",
      "commuter",
      "deal"
    ],
    "tag": "Short flight",
    "gateBuffer": 45,
    "commuteBuffer": 38,
    "immigrationOut": 76,
    "immigrationIn": 57,
    "fatigue": "Low",
    "image": "assets/img/portfolio/5.jpg"
  },
  {
    "id": "mnl-12",
    "city": "Manila",
    "country": "Philippines",
    "airport": "MNL",
    "origin": "ICN",
    "airline": "Philippine Airlines",
    "depart": "Thu 21:50",
    "arrive": "Fri 01:05",
    "returnDepart": "Sun 23:10",
    "returnArrive": "Mon 04:35",
    "price": 398000,
    "leave": 1,
    "score": 76,
    "mode": "max",
    "category": [
      "leave",
      "maxplay"
    ],
    "tag": "One day leave",
    "gateBuffer": 55,
    "commuteBuffer": 40,
    "immigrationOut": 90,
    "immigrationIn": 85,
    "fatigue": "High",
    "image": "assets/img/portfolio/6.jpg"
  },
  {
    "id": "sgn-13",
    "city": "Ho Chi Minh",
    "country": "Vietnam",
    "airport": "SGN",
    "origin": "ICN",
    "airline": "VietJet Air",
    "depart": "Fri 20:40",
    "arrive": "Sat 00:05",
    "returnDepart": "Mon 00:10",
    "returnArrive": "Mon 07:25",
    "price": 407000,
    "leave": 1,
    "score": 78,
    "mode": "max",
    "category": [
      "maxplay",
      "leave"
    ],
    "tag": "Food trip",
    "gateBuffer": 38,
    "commuteBuffer": 32,
    "immigrationOut": 86,
    "immigrationIn": 76,
    "fatigue": "High",
    "image": "assets/img/portfolio/1.jpg"
  },
  {
    "id": "cts-14",
    "city": "Sapporo",
    "country": "Japan",
    "airport": "CTS",
    "origin": "ICN",
    "airline": "Air Busan",
    "depart": "Fri 17:45",
    "arrive": "Fri 20:20",
    "returnDepart": "Sun 17:30",
    "returnArrive": "Sun 20:25",
    "price": 318000,
    "leave": 0.5,
    "score": 73,
    "mode": "relaxed",
    "category": [
      "relaxed",
      "weekend"
    ],
    "tag": "Half-day safer",
    "gateBuffer": 70,
    "commuteBuffer": 64,
    "immigrationOut": 65,
    "immigrationIn": 52,
    "fatigue": "Low",
    "image": "assets/img/portfolio/2.jpg"
  },
  {
    "id": "oka-15",
    "city": "Okinawa",
    "country": "Japan",
    "airport": "OKA",
    "origin": "ICN",
    "airline": "Peach",
    "depart": "Fri 21:00",
    "arrive": "Fri 23:25",
    "returnDepart": "Mon 07:10",
    "returnArrive": "Mon 09:45",
    "price": 377000,
    "leave": 0.5,
    "score": 83,
    "mode": "balanced",
    "category": [
      "weekend",
      "monday"
    ],
    "tag": "Morning return",
    "gateBuffer": 43,
    "commuteBuffer": 35,
    "immigrationOut": 67,
    "immigrationIn": 56,
    "fatigue": "Medium",
    "image": "assets/img/portfolio/3.jpg"
  },
  {
    "id": "han-16",
    "city": "Hanoi",
    "country": "Vietnam",
    "airport": "HAN",
    "origin": "ICN",
    "airline": "Vietnam Airlines",
    "depart": "Fri 18:30",
    "arrive": "Fri 21:25",
    "returnDepart": "Sun 23:30",
    "returnArrive": "Mon 05:40",
    "price": 455000,
    "leave": 0.5,
    "score": 69,
    "mode": "max",
    "category": [
      "maxplay"
    ],
    "tag": "Risky clock-out",
    "gateBuffer": 22,
    "commuteBuffer": 18,
    "immigrationOut": 85,
    "immigrationIn": 69,
    "fatigue": "High",
    "image": "assets/img/portfolio/4.jpg"
  },
  {
    "id": "kul-17",
    "city": "Kuala Lumpur",
    "country": "Malaysia",
    "airport": "KUL",
    "origin": "ICN",
    "airline": "AirAsia X",
    "depart": "Thu 22:20",
    "arrive": "Fri 04:00",
    "returnDepart": "Sun 23:35",
    "returnArrive": "Mon 07:10",
    "price": 462000,
    "leave": 1,
    "score": 75,
    "mode": "balanced",
    "category": [
      "leave",
      "monday"
    ],
    "tag": "One leave city break",
    "gateBuffer": 60,
    "commuteBuffer": 48,
    "immigrationOut": 82,
    "immigrationIn": 71,
    "fatigue": "Medium",
    "image": "assets/img/portfolio/5.jpg"
  },
  {
    "id": "cju-18",
    "city": "Jeju",
    "country": "Korea",
    "airport": "CJU",
    "origin": "GMP",
    "airline": "Eastar Jet",
    "depart": "Fri 19:05",
    "arrive": "Fri 20:15",
    "returnDepart": "Sun 20:45",
    "returnArrive": "Sun 21:55",
    "price": 139000,
    "leave": 0,
    "score": 95,
    "mode": "relaxed",
    "category": [
      "weekend",
      "commuter",
      "deal",
      "relaxed"
    ],
    "tag": "Domestic reset",
    "gateBuffer": 65,
    "commuteBuffer": 54,
    "immigrationOut": 30,
    "immigrationIn": 24,
    "fatigue": "Low",
    "image": "assets/img/portfolio/6.jpg"
  },
  {
    "id": "pus-19",
    "city": "Busan",
    "country": "Korea",
    "airport": "PUS",
    "origin": "GMP",
    "airline": "Korean Air",
    "depart": "Sat 07:40",
    "arrive": "Sat 08:45",
    "returnDepart": "Sun 19:20",
    "returnArrive": "Sun 20:25",
    "price": 128000,
    "leave": 0,
    "score": 89,
    "mode": "relaxed",
    "category": [
      "weekend",
      "deal",
      "relaxed"
    ],
    "tag": "Easy domestic",
    "gateBuffer": 78,
    "commuteBuffer": 63,
    "immigrationOut": 28,
    "immigrationIn": 22,
    "fatigue": "Low",
    "image": "assets/img/portfolio/1.jpg"
  },
  {
    "id": "uln-20",
    "city": "Ulaanbaatar",
    "country": "Mongolia",
    "airport": "UBN",
    "origin": "ICN",
    "airline": "MIAT",
    "depart": "Fri 22:00",
    "arrive": "Sat 00:40",
    "returnDepart": "Mon 06:30",
    "returnArrive": "Mon 10:50",
    "price": 498000,
    "leave": 1,
    "score": 72,
    "mode": "max",
    "category": [
      "maxplay",
      "leave"
    ],
    "tag": "Adventure sprint",
    "gateBuffer": 50,
    "commuteBuffer": 42,
    "immigrationOut": 82,
    "immigrationIn": 66,
    "fatigue": "High",
    "image": "assets/img/portfolio/2.jpg"
  }
];
window.personaData = [
  {
    "id": "office",
    "name": "금요일 저녁 퇴근형",
    "role": "강남 18:30 퇴근, 월요일 09:30 출근",
    "leave": "금요일 반차 불가, 월요일 반차 가능",
    "budget": 400000,
    "style": "balanced",
    "recommended": "fuk-01"
  },
  {
    "id": "nurse",
    "name": "교대근무 회복형",
    "role": "토요일 오전 출발 선호, 월요일 늦은 출근",
    "leave": "일요일 밤 도착 선호",
    "budget": 350000,
    "style": "relaxed",
    "recommended": "osa-03"
  },
  {
    "id": "max",
    "name": "짧아도 꽉 채우는 형",
    "role": "목요일 밤 출발 가능, 연차 1일 사용",
    "leave": "금요일 연차 가능",
    "budget": 520000,
    "style": "max",
    "recommended": "dad-04"
  }
];
